core/urls.py
from django.urls import path
from . import views


app_name = "core"


urlpatterns=[
    path('',views.show_all_persons_view,name="show_all_persons"),
    path('jobs-list/',views.show_all_jobs_view,name="show_all_jobs"),
    path('jobdetail-list/',views.show_all_personjobdetails_view,name="show_all_jobdetails"),
    path('person/create/',views.create_person_view,name="create_person"),
    path('person-detail/<int:pk>/',views.showpersondetail_view,name="show_person_detail"),
    path('job/create/',views.create_job_view,name="create_job"),
    path('jobdetail/create/',views.create_personjob_view,name="create_jobdetail"),
    ]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include("core.urls", namespace="core")),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
# Create your models here.
class Person(models.Model):
    first_name=models.CharField(_("First Name"), max_length=150)
    last_name=models.CharField(_("Last Name"), max_length=150)
    address=models.CharField(_("Address"),max_length=150)
    mobile = models.CharField(_("Mobile Phone"),max_length=15,unique=True)

    class Meta:
        verbose_name = "Person"
        verbose_name_plural = "Persons"
    def __str__(self):
        return self.get_full_name()

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()


class Job(models.Model):
    title_ar=models.CharField(_("Title Arabic"), max_length=150)
    title_en=models.CharField(_("Title English"), max_length=150)
    min_salary = models.DecimalField(_("Min Salary"),max_digits=10, decimal_places=2)

    class Meta:
        verbose_name = "Job"
        verbose_name_plural = "Jobs"

    def __str__(self):
        return self.title_en
    
class PersonJobDetail(models.Model):
    person=models.ForeignKey(Person,on_delete=models.CASCADE,related_name="rel_person")
    job=models.ForeignKey(Job,on_delete=models.CASCADE,related_name="rel_job")
    salary=models.DecimalField(_("Salary"),max_digits=10, decimal_places=2)
    years_of_experince=models.PositiveIntegerField(_("Years Of Experince"))

    class Meta:
        verbose_name = "PersonJobDetail"
        verbose_name_plural = "PersonJobDetails"

    def __str__(self):
        return f"{self.person} - {self.job}"

core/forms.py
from django import forms
from .models import Job,PersonJobDetail,Person
from django.core.validators import MinValueValidator




class PersonForm(forms.ModelForm):
    first_name=forms.CharField(label='First Name', min_length=3,required=True, max_length=150, widget=forms.TextInput(attrs={'class': 'form-control mb-3'}))
    last_name = forms.CharField(label='Last Name', min_length=3,required=True, max_length=150, widget=forms.TextInput(attrs={'class': 'form-control mb-3'}))
    address = forms.CharField(label='Address', min_length=3,required=True, max_length=150, widget=forms.TextInput(attrs={'class': 'form-control mb-3'}))
    mobile = forms.CharField(label='Mobile', min_length=7,required=True, max_length=15, widget=forms.TextInput(attrs={'class': 'form-control mb-3'}))
    class Meta:
        model = Person
        fields=('first_name','last_name','address','mobile')
  

class JobForm(forms.ModelForm):
    title_ar=forms.CharField(label='Job Title Ar', min_length=3,required=True, max_length=150, widget=forms.TextInput(attrs={'class': 'form-control mb-3','dir': 'rtl'}))
    title_en = forms.CharField(label='Job Title En', min_length=3,required=True, max_length=150, widget=forms.TextInput(attrs={'class': 'form-control mb-3'}))
    min_salary = forms.DecimalField(label='Min salary',max_digits=10,decimal_places=2,required=True, widget=forms.NumberInput(attrs={'class': 'form-control mb-3'}))
    class Meta:
        model = Job
        fields=('title_ar','title_en','min_salary')


    
class PersonJobDetailForm(forms.ModelForm):
    person=forms.ModelChoiceField(label='Select Person',queryset=Person.objects.all(), required=True,widget=forms.Select(attrs={'class': 'form-control mb-3'}))
    job=forms.ModelChoiceField(label='Select Job',queryset=Job.objects.all(), required=True,widget=forms.Select(attrs={'class': 'form-control mb-3'}))
    salary = forms.DecimalField(label='salary',max_digits=10,decimal_places=2,required=True, widget=forms.NumberInput(attrs={'class': 'form-control mb-3'}))
    years_of_experince=forms.IntegerField(label='ُYears Of Experince',required=True,widget=forms.NumberInput(attrs={'class': 'form-control mb-3'}),validators=[MinValueValidator(0)])
    class Meta:
        model = PersonJobDetail
        fields=('person','job','salary','years_of_experince')

core/views.py
from django.shortcuts import render,redirect
from .models import Job,Person,PersonJobDetail
from .filters import PersonFilter,JobDetailFilter,JobFilter
from django.urls import reverse
from .forms import JobForm,PersonForm,PersonJobDetailForm
# Create your views here.

def show_all_persons_view(request):
    person_list=Person.objects.all()
    person_list_filter=PersonFilter(request.GET,queryset=person_list)
    context={'persons':person_list_filter,}
    return render(request,"show_all_persons.html",context)

def show_all_jobs_view(request):
    job_list=Job.objects.all()
    job_list_filter=JobFilter(request.GET,queryset=job_list)
    context={'jobs':job_list_filter,}
    return render(request,"show_all_jobs.html",context)

def show_all_personjobdetails_view(request):
    jobdetail_list=PersonJobDetail.objects.all()
    jobdetail_list_filter=JobDetailFilter(request.GET,queryset=jobdetail_list)
    context={'jobdetails':jobdetail_list_filter,}
    return render(request,"show_all_personjobdetail.html",context)

def showpersondetail_view(request,pk):
    persondetail=Person.objects.get(pk=pk)
    all_person_jobs=PersonJobDetail.objects.filter(person__id=persondetail.id)
    context={"person_Var":persondetail,
             "all_person_jobs_Var":all_person_jobs,
             }
    return render(request,'show_person_detail.html',context)



def create_person_view(request):
    if request.method=="POST":
        form=PersonForm(request.POST,request.FILES)
        if form.is_valid():
            myform=form.save(commit=False)
            myform.save()
            form=PersonForm() #this line is for clear all form fields after submitting
            return redirect(reverse('core:show_all_persons'))
    else:
        form=PersonForm()
    return render(request,'person_create.html',{'person_form':form})



def create_job_view(request):
    if request.method=="POST":
        form=JobForm(request.POST,request.FILES)
        if form.is_valid():
            myform=form.save(commit=False)
            myform.save()
            form=JobForm() #this line is for clear all form fields after submitting
            return redirect(reverse('core:show_all_jobs'))
    else:
        form=JobForm()
    return render(request,'job_create.html',{'job_form':form})




def create_personjob_view(request):
    if request.method=="POST":
        form=PersonJobDetailForm(request.POST,request.FILES)
        if form.is_valid():
            myform=form.save(commit=False)
            myform.save()
            form=PersonJobDetailForm() #this line is for clear all form fields after submitting
            return redirect(reverse('core:show_all_jobdetails'))
    else:
        form=PersonJobDetailForm()
    return render(request,'personjobdetail_create.html',{'personjobdetail_form':form})

core/templates/job_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Job Create{% endblock %}

{% block content %} 

<main class="text-body-dark"> 
<div class="container">
    <div class="row my-5">
        <div class="col-md-12">
            <h4>Create New Job</h4>
            <form method='POST' enctype="multipart/form-data">
                {% csrf_token %}


                <label class="small font-weight-bold">{{ job_form.title_ar.label}}</label>
    {{ job_form.title_ar }}
    <label class="small font-weight-bold">{{ job_form.title_en.label}}</label>
    {{ job_form.title_en }}
    <label class="small font-weight-bold">{{ job_form.min_salary.label}}</label>
    {{ job_form.min_salary }}
  



    <button class="btn btn-success btn-block py-2 mb-4 mt-5 fw-bold w-100" type="submit" value="Create Job">Create</button>
    <hr class="mb-3">
                    




            </form>
        </div>
    </div>
</div>

</main>
{% endblock content %}

core/templates/person_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Person Create{% endblock %}

{% block content %} 

<main class="text-body-dark"> 
<div class="container">
    <div class="row my-5">
        <div class="col-md-12">
            <h4>Create New Person</h4>
            <form method='POST' enctype="multipart/form-data">
                {% csrf_token %}


                <label class="small font-weight-bold">{{ person_form.first_name.label}}</label>
    {{ person_form.first_name }}
    <label class="small font-weight-bold">{{ person_form.last_name.label}}</label>
    {{ person_form.last_name }}
    <label class="small font-weight-bold">{{ person_form.address.label}}</label>
    {{ person_form.address }}
    <label class="small font-weight-bold">{{ person_form.mobile.label}}</label>
    {{ person_form.mobile }}



    <button class="btn btn-success btn-block py-2 mb-4 mt-5 fw-bold w-100" type="submit" value="Create Person">Create</button>
    <hr class="mb-3">
                    




            </form>
        </div>
    </div>
</div>

</main>
{% endblock content %}

core/templates/personjobdetail_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}PersonJobDetail Create{% endblock %}

{% block content %} 

<main class="text-body-dark"> 
<div class="container">
    <div class="row my-5">
        <div class="col-md-12">
            <h4>Create New PersonJobDetail</h4>
            <form method='POST' enctype="multipart/form-data">
                {% csrf_token %}


                <label class="small font-weight-bold">{{ personjobdetail_form.person.label}}</label>
    {{ personjobdetail_form.person }}
    <label class="small font-weight-bold">{{ personjobdetail_form.job.label}}</label>
    {{ personjobdetail_form.job }}
    <label class="small font-weight-bold">{{ personjobdetail_form.salary.label}}</label>
    {{ personjobdetail_form.salary }}
    <label class="small font-weight-bold">{{ personjobdetail_form.years_of_experince.label}}</label>
    {{ personjobdetail_form.years_of_experince }}



    <button class="btn btn-success btn-block py-2 mb-4 mt-5 fw-bold w-100" type="submit" value="Create PersonJobDetail">Create</button>
    <hr class="mb-3">
                    




            </form>
        </div>
    </div>
</div>

</main>
{% endblock content %}

core/templates/show_all_jobs.html
{% extends "base.html" %}
{% load static %}

{% block title %}Show Jobs{% endblock %}
{% block content %} 

<main class="text-body-dark"> 
    <div class="container">
        <div class="row my-5">
            <div class="col-md-12"> 
                <h4>ALL Jobs</h4>
                <a href="{% url 'core:create_job' %}" class="btn btn-indigo btn-primary btn-sm m-0 float-end">Create</a>
          
                 <form  id="myfilterform" method="get" class="mt-5 mb-5 float-start" >
                     
                    
                     {{jobs.form.as_p}} 
                     <div class='text-center'>   
                     <button id="subbutton" class="btn btn-sm btn-success">check</button> 
                     </div>  
                </form>  

 
              
              

                <table class="table table-striped table-responsive-md  btn-table">
                    <caption class="text-dark fw-bold">Number: {{jobs.qs.count}}</caption>
                    <thead>
                      <tr>
                        <th>#</th>
                        <th>Job id</th>
                        
                        <th>Job Title Ar</th>
                        <th>Job Title En</th>
                        <th>Min Salary</th>
                      </tr>
                    </thead>
                    {% comment %} href="{% url 'core:showdest_view' person.id %}" {% endcomment %}
                    <tbody>
                    {% for job in jobs.qs %}
                      <tr>
                        <th scope="row"></th>
                        <td><a >{{job.id}}</a></td>
                        <td>{{job.title_ar}}</td>
                        <td>{{job.title_en}}</td>
                        <td>{{job.min_salary}}</td>

                        

     
                        
                      </tr>
                      {% endfor %} 
                    </tbody>
                    
                    </table>
            </div>
        </div>
    </div>
    
    </main>



{% endblock content%}

core/templates/show_all_personjobdetail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Show PersonJobDetails{% endblock %}
{% block content %} 

<main class="text-body-dark"> 
    <div class="container">
        <div class="row my-5">
            <div class="col-md-12"> 
                <h4>ALL JobDetails</h4>
                <a href="{% url 'core:create_jobdetail' %}" class="btn btn-indigo btn-primary btn-sm m-0 float-end">Create</a>
          
                 <form  id="myfilterform" method="get" class="mt-5 mb-5 float-start" >
                     
                    
                     {{jobdetails.form.as_p}} 
                     <div class='text-center'>   
                     <button id="subbutton" class="btn btn-sm btn-success">check</button> 
                     </div>  
                </form>  

 
              
              

                <table class="table table-striped table-responsive-md  btn-table">
                    <caption class="text-dark fw-bold">Number: {{jobdetails.qs.count}}</caption>
                    <thead>
                      <tr>
                        <th>#</th>
                        <th>PersonJobDetail id</th>
                        
                        <th>Job</th>
                        <th>Person</th>
                        <th>Salary</th>
                        <th>Years of Experince</th>
                      </tr>
                    </thead>
                    {% comment %} href="{% url 'core:showdest_view' person.id %}" {% endcomment %}
                    <tbody>
                    {% for jobdetail in jobdetails.qs %}
                      <tr>
                        <th scope="row"></th>
                        <td><a >{{jobdetail.id}}</a></td>
                        <td>{{jobdetail.job}}</td>
                        <td>{{jobdetail.person}}</td>
                        <td>{{jobdetail.salary}}</td>
                        <td>{{jobdetail.years_of_experince}}</td>
                        

     
                        
                      </tr>
                      {% endfor %} 
                    </tbody>
                    
                    </table>
            </div>
        </div>
    </div>
    
    </main>



{% endblock content%}

core/templates/show_all_persons.html
{% extends "base.html" %}
{% load static %}

{% block title %}Testing|Show Persons{% endblock %}
{% block content %} 

<main class="text-body-dark"> 
    <div class="container">
        <div class="row my-5">
            <div class="col-md-12"> 
                <h4>ALL Persons</h4>
                <a href="{% url 'core:create_person' %}" class="btn btn-indigo btn-primary btn-sm m-0 float-end">Create</a>
          
                 <form  id="myfilterform" method="get" class="mt-5 mb-5 float-start" >
                     
                    
                     {{persons.form.as_p}} 
                     <div class='text-center'>   
                     <button id="subbutton" class="btn btn-sm btn-success">check</button> 
                     </div>  
                </form>  

 
              
              

                <table class="table table-striped table-responsive-md  btn-table">
                    <caption class="text-dark fw-bold">Number: {{persons.qs.count}}</caption>
                    <thead>
                      <tr>
                        <th>#</th>
                        <th>Person id</th>
                        
                        <th>Person fullname</th>
                        <th>Address</th>
                        <th>Mobile</th>
                      </tr>
                    </thead>
  
                    <tbody>
                    {% for person in persons.qs %}
                      <tr> 
                        <th scope="row"></th>
                        <td><a href="{% url 'core:show_person_detail' person.id %}"  >{{person.id}}</a></td>
                        <td><a href="{% url 'core:show_person_detail' person.id %}"  >{{person.get_full_name}}</a></td>
                        <td>{{person.address}}</td>
                        <td>{{person.mobile}}</td>

                        


                      </tr>
                      {% endfor %} 
                    </tbody>
                    
                    </table>
            </div>
        </div>
    </div>
    
    </main>



{% endblock content%}

core/templates/show_person_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Person Detail Show{% endblock %}

{% block content %}


<main class="text-body-dark">

  
  

  <section class="p-5 w-100">
    <div class="col-md-12 ">
      <div class="h-100 p-5 border rounded-3 ">
        <h1  class="display-5 fw-bold text-body-dark">Person Details</h1>
        <p  class=" fw-bold text-body-dark">ID: {{person_Var.id}}</p>
        <p  class=" fw-bold text-body-dark">Fullname: {{person_Var.get_full_name}}</p>
        <p  class=" fw-bold text-body-dark">Address: {{person_Var.address}}</p>
        <p  class=" fw-bold text-body-dark">Mobile: {{person_Var.mobile}}</p>
      </div>
    </div>
  </section>


  <section> 
    <div class="container">
        <div class="row my-5">
            <div class="col-md-12"> 
                <h4>ALL Person Jobs</h4>
                
 

 
              
              

                <table class="table table-striped table-responsive-md  btn-table">
                    <caption class="text-dark fw-bold">Number: {{all_person_jobs_Var.count}}</caption>
                    <thead>
                      <tr>
                        <th>#</th>
                        <th>PersonJobDetail id</th>
                        
                        <th>Job</th>
                        <th>Person</th>
                        <th>Salary</th>
                        <th>Years of Experince</th>
                      </tr>
                    </thead>

                    <tbody>
                    {% for jobdetail in all_person_jobs_Var %}
                      <tr>
                        <th scope="row"></th>
                        <td><a >{{jobdetail.id}}</a></td>
                        <td>{{jobdetail.job}}</td>
                        <td>{{jobdetail.person}}</td>
                        <td>{{jobdetail.salary}}</td>
                        <td>{{jobdetail.years_of_experince}}</td>
                        

     
                        
                      </tr>
                      {% endfor %} 
                    </tbody>
                    
                    </table>
            </div>
        </div>
    </div>
    

  </section>

</main>

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <title>{% block title %}testing{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% block stylesheet %}{% endblock %}">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/color-modes.js' %}"></script>
  </head>
  <body >

    <main>
    {% include "header.html" %}
        <main class="pt-5">
          <div id="content">{% block content %} {% endblock %}</div>
        </main>


      </main>
      
      
          </body>
      </html>
      

templates/header.html
{% load static %}

<div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">

        <span class="fs-4">Task Project</span>
      </a>

      <ul class="nav nav-pills">
        <li class="nav-item"><a href="{% url "core:show_all_persons" %}" class="nav-link">Show All Persons</a></li>
        <li class="nav-item"><a href="{% url "core:show_all_jobs" %}" class="nav-link">Show All Jobs</a></li>
        <li class="nav-item"><a href="{% url "core:show_all_jobdetails" %}" class="nav-link">Show All PersonJobDetails</a></li>
        <li class="nav-item"><a href="{% url "core:create_person" %}" class="nav-link">Create Person</a></li>
        <li class="nav-item"><a href="{% url "core:create_job" %}" class="nav-link">Create Job</a></li>
        <li class="nav-item"><a href="{% url "core:create_jobdetail" %}" class="nav-link">Create PersonJob</a></li>
      </ul>
    </header>
</div>